name: Feature Request
description: WIP
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Hello
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: Test 1
          required: true
        - label: Test 2
          required: true
