name: Feature Request
description: WIP
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Hello foo
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: Test 1
          required: true
        - label: Test 2
          required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
