
name: 🐛 Bug Report
description: Submit a bug report to help us improve Streamlit.
labels: [bug, needs triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search [here](https://github.com/streamlit/streamlit/issues) to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Summary
    description: Type here a clear and concise description of the bug. Aim for 2-3 sentences.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproducible Code Example 
    render: python
    description: |
        If applicable, please provide a [self-contained minimal code example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into.
        
        If we can copy it, run it, and see it right away, there's a much higher chance we will be able to help you.
    placeholder: |
        import streamlit as st
        
        st.write("Hello World")
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Please provide the steps we should take to reproduce the bug.
    placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: Explain what you expect to happen when you go through the steps above, assuming there were no bugs.
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    placeholder: |
        Error message:
        
        ```
        streamlit.errors.StreamlitAPIException ...
        ```
    description:  |
        Explain the buggy behavior you experience when you go through the steps above.
        If you have error messages or stack traces please provide them here as well.
        If applicable, add screenshots to help explain your problem. 
  validations:
    required: false
- type: dropdown
  attributes:
    label: Is this a regression?
    description: That is, did this use to work the way you expected in the past?
    options:
      - "Yes"
      - "No"
      - "I don't know"
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: |
        What operating system is your Streamlit app running on?
        
        _You can add more details in the `Additional Information` section below._
    multiple: true
    options:
      - Linux
      - Windows
      - macOS
      - Other
  validations:
    required: false
- type: input
  attributes:
    label: Streamlit Version
    description: |
      What Streamlit version are you using? You can find it via:

      ```bash
      streamlit version
      ```
  validations:
    required: false
- type: input
  attributes:
    label: Python Version
    description: |
      What Python version are you using? You can find the Python version via:

      ```bash
      python --version
      ```
  validations:
    required: false
- type: dropdown
  attributes:
    label: Browser
    description: |
        What browser do you use to access the Streamlit app?
        
        _You can add more details in the `Additional Information` section below._
    multiple: true
    options:
      - Chrome
      - Safari
      - Firefox
      - Edge
      - Opera
      - Other
  validations:
    required: false
- type: dropdown
  attributes:
    label: Virtual Environment
    description: |
        Are you using a virtual environment to run the Streamlit app?
        
        _You can add more details in the `Additional Information` section below._
    multiple: true
    options:
      - Conda
      - Pipenv
      - Venv
      - Poetry
      - Virtualenv
      - Pyenv
      - Pex
      - Other
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering! 
      For example, did this bug come from https://discuss.streamlit.io or another site? Link the original source here!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
